version: "3"
services:
    db:
        container_name: gnnie-db-postgres
        image: "postgres:latest"
        env_file: 
            - ./.env
        ports:
            - 5432:5432
    api:
        container_name: gnnie-api
        image: "arogyak/gnnie-api"
        env_file: 
            - ./.env
        ports:
            - 8020:8080
    # frontend:
    #     container_name: baato-website
    #     image: "arogyak/gnnie-frontend"
    #     restart: always
    #     env_file:
    #         - ./.env
    #     ports:
    #         - 8010:3000
