version: "3"
services:
    db:
        container_name: gnnie-db-postgres
        image: "postgres:latest"
        env_file: 
            - ./.env
        ports:
            - 5432:5432
    api:
        container_name: gnnie-api
        image: "arogyak/gnnie-api"
        env_file: 
            - ./.env
        ports:
            - 8081:8080
    