version: "3"
services:
    db:
        container_name: gnnie-db-postgres
        image: "postgres:latest"
        env_file: 
            - ./.env
        ports:
            - 5432:5432
    platform-client:
        container_name: gnnie-platform-client
        image: "arogyak/gnnie-platform-client"
        restart: always
        env_file:
            - ./.env
        ports:
            - 8020:3000
    platform-service:
        container_name: gnnie-platform-service
        image: "arogyak/gnnie-platform-service"
        env_file: 
            - ./.env
        ports:
            - 8021:8080
        volumes:
            - ./raw-files:/app/raw-files:rw
            - ./model-files:/app/model-files:rw
    model-service:
        container_name: gnnie-model-service
        image: "arogyak/gnnie-model-service"
        env_file: 
            - ./.env
        ports:
            - 8022:5000
        volumes:
            - ./raw-files:/app/raw-files
            - ./model-files:/app/model-files

