version: "3"
services:
    # nginx:
    #     build:
    #         context: ./nginx
    #     env_file: 
    #         - ./.env
    #     ports:
    #         - 80:80
    #         - 443:443
    #     volumes:
    #         - /etc/letsencrypt:/etc/letsencrypt
    #     # depends_on:
    #     #     - application
    db:
        container_name: gnnie-db-postgres
        image: "postgres:latest"
        env_file: 
            - ./.env
        ports:
            - 5432:5432
    api:
        container_name: gnnie-api
        image: "arogyak/gnnie-api"
        env_file: 
            - ./.env
        ports:
            - 8020:8080
    model-service:
        container_name: gnnie-model-service
        image: "arogyak/gnnie-model-service"
        env_file: 
            - ./.env
        ports:
            - 8030:5000
    frontend:
        container_name: gnnie-client
        image: "arogyak/gnnie-client"
        restart: always
        env_file:
            - ./.env
        ports:
            - 8010:3000
