version: "3"
services:
    db:
        container_name: gnnie-db-postgres
        image: "postgres:latest"
        env_file: 
            - ./.env
        ports:
            - 5432:5432
    platform-client:
        container_name: gnnie-platform-client
        image: "arogyak/gnnie-platform-client-amd64"
        restart: always
        env_file:
            - ./.env
        ports:
            - 8020:3000
    platform-service:
        container_name: gnnie-platform-service
        image: "arogyak/gnnie-platform-service-amd64"
        env_file: 
            - ./.env
        ports:
            - 8021:8080
        volumes:
            - ./data:/app/user-data:rw
    model-service:
        container_name: gnnie-model-service
        image: "arogyak/gnnie-model-service-amd64"
        env_file: 
            - ./.env
        ports:
            - 8022:5000
        volumes:
            - ./data:/app/data

